# 1. SETUP AND BASICS

If no torch yet,

```
!pip install torch
```

In [1]:
import torch

## 1.1. What is a "tensor"?

In [19]:
# python range returns a list from 0 to 11

list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

Tensor is an *n-th dimensional array*.

This is not new. A simple array like **[1, 2, 3]** is a tensor with *1 dimension and 3 elements* (1x3). We know this as a **vector**.

An array that looks like this:

```Python
array = [[0, 1, 2],[3, 4, 5]]
```

||column 1|column 2|column3| 
|-----|-------|------|------|
|row 1|0|1|2| 
|row 2|3|4|5|

-- is a *2 dimensional tensor with 2 rows and 3 columns* (2x3). We know this as a **matrix**.

In [ ]:
'''
So 'arange' is torch's version of 'range', but returns a tensor instead of list.
'''

x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
'''
"numel" means "number of elements", which is like Python's "len".
'''

x.numel()

12

## 1.2. The shape of a tensor

In [ ]:
'''
pretty straightforward, shape describes the tensor's dimentions. In this case, it's a 1D tensor with 12 elements. We also call this a vector.
'''

x.shape

torch.Size([12])

In [ ]:
'''
reshape transforms the dimensions of a tensor, but keep the same elements. 
Here, we transform 1D - 12 elements into 2D - 3 rows 4 columns.
The number of elements is still 12.
'''

X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Let's call:
- number of tensor elements: n
- shape_width: w
- shape_height: h

We can infer that:
w = n / h
h = n / w

We can use -1 as a placeholder, and torch will calculate it for us.

In [ ]:
'''
Let's change our tensor from 2D(3, 4) to 2D(4, 3) by typing (4, -1).
Torch will calculate -1 is 3 from n/w (12 / 4 = 3)
'''

x = x.reshape(4, -1)
x

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [ ]:
'''
This generates a 3D tensor (like a cube) with 2 layers, each having 3 rows and 4 columns, filled with zeros.
'''

torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
'''A 2D tensor with 3 rows and 4 columns filled with random numbers.  We also call 2D tensors matrices.'''

torch.randn(3, 4)

tensor([[ 0.0549, -0.0112, -0.2160, -0.7329],
        [-0.7643,  0.4343, -0.2090,  0.4878],
        [ 0.0269,  0.3261,  1.1710, -0.4812]])

In [ ]:
'''
Looking closely at this.
It's a 1D tensor with 3 elements.
Each element is a 1D tensor with 4 elements.
'''

torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

# 2. Tensor indexing

Tensor indexing is not too different from indexing arrays, just with more dimensions most of the time.


Let's revisit our x tensor.

In [21]:
x

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

We can access the third row *[6, 7, 8]* by writing

```Python
x[2] ## since indexing starts at 0
```

In [22]:
x[2]

tensor([6., 7., 8.])

Let's retrieve the last row by

```Python
x[-1]
```

In [23]:
x[-1]

tensor([ 9., 10., 11.])

How about the last 2 rows? Or the second row till the second to last? We use a the ":" to indicates:

```Python
[:n] ## all elements from the beginning up to n
[n:] ## n and all elements after n till the end.

# In our case:
x[-2:] ## 'All elements from the second to last row until the end'
x[0:-2] ## 'All elements from the second row to the second-to-last row.
```

In [27]:
x[-2:], x[0:-2]

(tensor([[ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]))

We can write the elements, too. 

Let's replace the *first element* of the *third row (3, 1)* with the number 80

In [28]:
x

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [29]:
x[3, 1] = 80
x

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 80., 11.]])

# 3. Tensor operations